import Head from 'next/head'

export default function Blog() {

    return (
        <div>
        <Head>
          <title>Que es side server render?</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          //importar diseño de estilo home 
            <link rel="stylesheet" href="../styles/Home.module.css" />
        </Head>
  
        <main>
          <h1 >
           Que es el side server render?
          </h1>
  
          <p>
          La renderización del lado del servidor (SSR) es una técnica popular para renderizar una aplicación de una sola página (SPA) del lado del cliente en el servidor y enviar una página completamente renderizada al cliente. Esto permite que los componentes dinámicos se presenten como marcado HTML estático.
          </p>
  
          <div>
            <p> algunas ventajas pueden ser:</p>
            <ul>
                <li>
                    <p>
                        <strong>
                            Renderiza la aplicación de una sola página
                        </strong>
                    </p>
                </li>
                <li>
                    <p>
                        <strong>
                            No requiere de una conexión a un servidor
                        </strong>
                    </p>
                </li>

            </ul>
          </div>
        </main>
        <br/>
      </div>
    );
}